title: Andrew Gambardella
email: atgambardella@weblab.t.u-tokyo.ac.jp
description: >- # This is a brief description of your website.
  Andrew Gambardella's personal academic website
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site
twitter_username: atgambardella
github_username:  atgambardella

languages: ["en", "ja"]
default_lang: "en"

theme: minima

